In [2]:
import pandas as pd

data = {
    "Name": [
        "Alice", "Bob", "Charlie", "David", "Evelyn",
        "Frank", "Grace", "Henry", "Isla", "Jack",
        "Karen", "Leo", "Mia", "Noah", "Olivia",
        "Paul", "Quinn", "Ruby", "Sam", "Tina"
    ],
    "Age": [25, 32, 37, 29, 41, 28, 34, 45, 26, 31, 39, 27, 33, 36, 30, 42, 24, 38, 35, 29],
    "Department": [
        "HR", "Engineering", "Sales", "Marketing", "Engineering",
        "Finance", "Support", "Operations", "HR", "Sales",
        "Engineering", "Support", "Marketing", "Finance", "Operations",
        "Engineering", "HR", "Sales", "Support", "Marketing"
    ],
    "Salary": [
        50000, 75000, 62000, 58000, 80000,
        54000, 52000, 70000, 51000, 64000,
        82000, 53000, 60000, 56000, 68000,
        79000, 49500, 65500, 54500, 61000
    ],
}

df = pd.DataFrame(data)

print(df)

       Name  Age   Department  Salary
0     Alice   25           HR   50000
1       Bob   32  Engineering   75000
2   Charlie   37        Sales   62000
3     David   29    Marketing   58000
4    Evelyn   41  Engineering   80000
5     Frank   28      Finance   54000
6     Grace   34      Support   52000
7     Henry   45   Operations   70000
8      Isla   26           HR   51000
9      Jack   31        Sales   64000
10    Karen   39  Engineering   82000
11      Leo   27      Support   53000
12      Mia   33    Marketing   60000
13     Noah   36      Finance   56000
14   Olivia   30   Operations   68000
15     Paul   42  Engineering   79000
16    Quinn   24           HR   49500
17     Ruby   38        Sales   65500
18      Sam   35      Support   54500
19     Tina   29    Marketing   61000

In [ ]:
#Exercise 1: view the first 5 rows of the DataFrame
df.head()

      Name  Age   Department  Salary
0    Alice   25           HR   50000
1      Bob   32  Engineering   75000
2  Charlie   37        Sales   62000
3    David   29    Marketing   58000
4   Evelyn   41  Engineering   80000

In [ ]:
#Exercise 2: view the last 5 rows of the Dataframe
df.tail()

     Name  Age   Department  Salary
15   Paul   42  Engineering   79000
16  Quinn   24           HR   49500
17   Ruby   38        Sales   65500
18    Sam   35      Support   54500
19   Tina   29    Marketing   61000

In [ ]:
#Exercise 3: Get basic info about the DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        20 non-null     str
 1   Age         20 non-null     int64
 2   Department  20 non-null     str
 3   Salary      20 non-null     int64
dtypes: int64(2), str(2)
memory usage: 772.0 bytes

In [ ]:
#Exercise 4: check the shape of the DataFrame
df.shape

(20, 4)

In [ ]:
#Exercise 1: Use .loc to get the name and age of the passenger with index 12
df.loc[12, ['Name', 'Age']]

Name    Mia
Age      33
Name: 12, dtype: object

In [ ]:
#Exercise 2: Use .iloc to get the first 5 rows and the first 3 columns
df.iloc[0:5, 0:3]

      Name  Age   Department
0    Alice   25           HR
1      Bob   32  Engineering
2  Charlie   37        Sales
3    David   29    Marketing
4   Evelyn   41  Engineering

In [25]:
# Load Titanic dataset directly from GitHub
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

print(df.head())
print(df.columns)

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [21]:
#Exercise 3: Use .loc to get all passengers in 1st class who are female
df.loc[(df['Pclass'] == 1) & (df['Sex'] == 'female')]
#passengers = df[df['Pclass'] == 1]
#df.loc[passengers['female'] 'female']
#df.loc['Pclass', 'Name', 'Sex']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [30]:
#Exercise 4: use .iloc to get the age of the 10th passenger (by position)
df.iloc[9, 5]
print(df.iloc[9, 5])

14.0

In [28]:
print(df.head(11))

    PassengerId  Survived  Pclass  \
0             1         0       3
1             2         1       1
2             3         1       3
3             4         1       1
4             5         0       3
5             6         0       3
6             7         0       1
7             8         0       3
8             9         1       3
9            10         1       2
10           11         1       3

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                              Heikkinen, Miss. Laina  female  26.0      0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                            Allen, Mr. William Henry    male  35.0      0
5                                    Moran, Mr. James    male   NaN      0
6                             McCarthy, Mr. Timothy J    male  54.0      0
7                      Palsson, Master. Gosta Leonard    male   2.0      3
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1

    Parch            Ticket     Fare Cabin Embarked
0       0         A/5 21171   7.2500   NaN        S
1       0          PC 17599  71.2833   C85        C
2       0  STON/O2. 3101282   7.9250   NaN        S
3       0            113803  53.1000  C123        S
4       0            373450   8.0500   NaN        S
5       0            330877   8.4583   NaN        Q
6       0             17463  51.8625   E46        S
7       1            349909  21.0750   NaN        S
8       2            347742  11.1333   NaN        S
9       0            237736  30.0708   NaN        C
10      1           PP 9549  16.7000    G6        S

In [32]:
#Exercise 5: Use .loc to get the Fare and Survived values for passengers with index 100 to 105
df.loc[100:105, ['Fare', 'Survived']]

        Fare  Survived
100   7.8958         0
101   7.8958         0
102  77.2875         0
103   8.6542         0
104   7.9250         0
105   7.8958         0

In [43]:
#Exercise 1: summarize the numeric columns
df['PassengerId'].describe()

count    891.000000
mean     446.000000
std      257.353842
min        1.000000
25%      223.500000
50%      446.000000
75%      668.500000
max      891.000000
Name: PassengerId, dtype: float64

In [44]:
#Exercise 1: summarize the numeric columns
df['Survived'].describe()

count    891.000000
mean       0.383838
std        0.486592
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        1.000000
Name: Survived, dtype: float64

In [45]:
#Exercise 1: summarize the numeric columns
df['Pclass'].describe()

count    891.000000
mean       2.308642
std        0.836071
min        1.000000
25%        2.000000
50%        3.000000
75%        3.000000
max        3.000000
Name: Pclass, dtype: float64

In [46]:
#Exercise 1: summarize the numeric columns
df['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [47]:

#Exercise 1: summarize the numeric columns
df['SibSp'].describe()

count    891.000000
mean       0.523008
std        1.102743
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        8.000000
Name: SibSp, dtype: float64

In [48]:
#Exercise 1: summarize the numeric columns
df['Parch'].describe()

count    891.000000
mean       0.381594
std        0.806057
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        6.000000
Name: Parch, dtype: float64

In [49]:
#Exercise 1: summarize the numeric columns
df['Fare'].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

In [ ]:

#Exercise 2: Use .value_counts() to see counts for embarkation ports.
df['Embarked'].value_counts

<bound method IndexOpsMixin.value_counts of 0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: str>

In [51]:
#Exercise 3: Use .value_counts() to count passenger classes.
df['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [ ]:
#Exercise 4: Show the average (mean) age of passengers.
df['Age'].mean()

np.float64(29.69911764705882)

In [53]:
#Exercise 5: Show the maximum fare paid.
df['Fare'].max()

np.float64(512.3292)

In [54]:
#Exercise 6: Show how many unique names are in the dataset.
df['Name'].nunique()

891

In [55]:
#Exercise 7: Show counts for values in the Sex column
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [57]:
#Exercise 8: Show how many unique values are in each column.
print(df.nunique())

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [ ]:
#Section 2, Dropping Data
#Exercise 1: Drop the Email column and store the result in a new variable.

data = {
"Name": ["Alice", "Bob", "Charlie", "David"],
"Age": [25, 30, 35, 40],
"City": ["NYC", "LA", "Chicago", "Miami"],
"Email": ["a@example.com", "b@example.com", "c@example.com", "d@example.com"],
}

df = pd.DataFrame(data)

df_minus_Email = df.drop('Email', axis = 1)
print(df_minus_Email)

      Name  Age     City
0    Alice   25      NYC
1      Bob   30       LA
2  Charlie   35  Chicago
3    David   40    Miami

In [ ]:
#Section 2, Dropping Data
#Exercise 2: Drop the row with index 2 in place. #axis = 0 for rows is the default
data = {
"Name": ["Alice", "Bob", "Charlie", "David"],
"Age": [25, 30, 35, 40],
"City": ["NYC", "LA", "Chicago", "Miami"],
"Email": ["a@example.com", "b@example.com", "c@example.com", "d@example.com"],
}

df = pd.DataFrame(data)
df.drop(2, axis=0, inplace=True)
print(df)

    Name  Age   City          Email
0  Alice   25    NYC  a@example.com
1    Bob   30     LA  b@example.com
3  David   40  Miami  d@example.com

In [ ]:
#Section 2, Dropping Data
#Exercise 3: Drop the City and Email columns, and assign the result back to df.
data = {
"Name": ["Alice", "Bob", "Charlie", "David"],
"Age": [25, 30, 35, 40],
"City": ["NYC", "LA", "Chicago", "Miami"],
"Email": ["a@example.com", "b@example.com", "c@example.com", "d@example.com"],
}

df = pd.DataFrame(data)
df = df.drop(['City', 'Email'], axis=1)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

In [ ]:
#Section 2, Dropping Data
#Exercise 4: Drop the first and last row, and store the result in df_trimmed.
data = {
"Name": ["Alice", "Bob", "Charlie", "David"],
"Age": [25, 30, 35, 40],
"City": ["NYC", "LA", "Chicago", "Miami"],
"Email": ["a@example.com", "b@example.com", "c@example.com", "d@example.com"],
}

df = pd.DataFrame(data)
df_trimmed = df.drop([0, 3], axis=0) 
print(df_trimmed)

      Name  Age     City          Email
1      Bob   30       LA  b@example.com
2  Charlie   35  Chicago  c@example.com

In [97]:
#Section 2, Missing Data
#Exercise 1: View the first 5 rows of the DataFrame.
import pandas as pd
import numpy as np

data = {
"Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
"Age": [25, np.nan, 35, 40, None],
"City": ["NYC", "LA", None, "Miami", "Boston"],
}

df = pd.DataFrame(data)

df.head()

      Name   Age    City
0    Alice  25.0     NYC
1      Bob   NaN      LA
2  Charlie  35.0     NaN
3    David  40.0   Miami
4      Eva   NaN  Boston

In [100]:
#Section 2, Missing Data
#Exercise 2: Show where values are missing.
import pandas as pd
import numpy as np

data = {
"Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
"Age": [25, np.nan, 35, 40, None],
"City": ["NYC", "LA", None, "Miami", "Boston"],
}

df = pd.DataFrame(data)

df.isnull()

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

In [101]:
#Section 2, Missing Data
#Exercise 3: Count missing values by column.


import pandas as pd
import numpy as np

data = {
"Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
"Age": [25, np.nan, 35, 40, None],
"City": ["NYC", "LA", None, "Miami", "Boston"],
}

df = pd.DataFrame(data) 

df.isnull().sum()

Name    0
Age     2
City    1
dtype: int64

In [ ]:
#Section 2, Missing Data
#Exercise 4: Drop rows with missing data.

In [ ]:
#Section 2, Missing Data
#Exercise 6 (skips from 4 to 6): Drop columns with missing data.

In [ ]:
#Section 2, Missing Data
#Exercise 8 (skips from 6 to 8): Fill missing Age values with the mean.

In [ ]:
#Section 2, Missing Data
#Exercise 9: Fill missing City values with "Unknown".

In [ ]:
#Section 3, Duplicates:
#Exercise 1: Find which rows are duplicates across all columns.
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "Diana"],
"Age": [25, 30, 35, 25, 30, 40],
"City": ["NYC", "LA", "SF", "NYC", "LA", "NYC"],
}

df = pd.DataFrame(data)

In [ ]:
#Section 3, Duplicates:
#Exercise 2: Drop duplicates rows, keeping the first occurrence.

In [ ]:
#Section 3, Duplicates:
#Exercise 3: Drop duplicate rows, keeping only the last occurrence.

In [ ]:
#Section 3, Duplicates:
#Exercise 4: Drop all duplicates, removing both the original and duplicate rows.

In [ ]:
#Section 3, Data Wrangling Essentials
#Exercise Set 1
#Exercise 1: Change fname to FirstName and lname to LastName.
import pandas as pd

data = {
"fname": ["Alice", "Bob", "Charlie"],
"lname": ["Smith", "Jones", "Brown"],
"ctry": ["USA", "Canada", "UK"],
}

df = pd.DataFrame(data)

In [ ]:
#Section 3, Data Wrangling Essentials
#Exercise Set 1
#Exercise 2: Change all column names to ['FirstName', 'LastName', 'Country']

In [ ]:
#Section 3, Data Wrangling Essentials
#Exercise Set 2
#Exercise 1: Rename Dept to Department and Sal to Salary.
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie"],
"Dept": ["HR", "Finance", "IT"],
"Sal": [60000, 70000, 80000],
}

df = pd.DataFrame(data)

In [ ]:
#Section 3, Data Wrangling Essentials
#Exercise Set 2
#Exercise 2: Reorder columns so Salary appears first, followed by Name and Department.

In [ ]:
#Section 3, Data Wrangling Essentials
#Exercise Set 2
#Exercise 3: Print the updated DataFrame.

In [ ]:
#Section 3, Data Wrangling Essentials
#Exercise Set 3: Groupby and Agg
#Exercise 1: Group the datea by Store and use .agg() to find the average Sales and average Profit for each store.

import pandas as pd

data = {
"Store": ["A", "A", "A", "B", "B", "C", "C", "C", "C"],
"Product": ["Apples", "Oranges", "Bananas", "Apples", "Bananas", "Oranges", "Apples", "Bananas", "Bananas"],
"Sales": [100, 80, 90, 120, 110, 60, 95, 85, 75],
"Profit": [30, 25, 20, 40, 35, 15, 32, 22, 18],
}

df = pd.DataFrame(data)
print(df.head())

In [ ]:
#Section 3, Data Wrangling Essentials
#Exercise Set 3: Groupby and Agg
#Exercise 2: Group by Product and get the maximum Sales and minimum Profit.

In [ ]:
#Section 3, Data Wrangling Essentials
#Exercise Set 3: Groupby and Agg
#Exercise 3: Group by Store and return the average Sales and maximum Profit, but name the columns Avg_Sales and Max_Profit.

In [ ]:
#Section 3, Data Wrangling Essentials
#Exercise Set 3: Groupby and Agg
#Exercise 4: BONUS: Group by both Store and Product, and find the total Sales using .agg().

In [ ]:
#Section 3, Data Wrangling Essentials
#Exercise Set 4: Joining
#Exercise 1: Join df_orders to df_customers on the index
 
import pandas as pd

df_customers = pd.DataFrame({
"CustomerName": ["Alice", "Bob", "Charlie"]
}, index=[101, 102, 103])

df_orders = pd.DataFrame({
"OrderTotal": [250, 300, 400]
}, index=[101, 102, 103])

In [ ]:
#Section 3, Data Wrangling Essentials
#Exercise Set 4: Joining
#Exercise 2: Add a new column to df_customers with the city data from df_cities.