In [2]:
import pandas as pd

data = {
    "Name": [
        "Alice", "Bob", "Charlie", "David", "Evelyn",
        "Frank", "Grace", "Henry", "Isla", "Jack",
        "Karen", "Leo", "Mia", "Noah", "Olivia",
        "Paul", "Quinn", "Ruby", "Sam", "Tina"
    ],
    "Age": [25, 32, 37, 29, 41, 28, 34, 45, 26, 31, 39, 27, 33, 36, 30, 42, 24, 38, 35, 29],
    "Department": [
        "HR", "Engineering", "Sales", "Marketing", "Engineering",
        "Finance", "Support", "Operations", "HR", "Sales",
        "Engineering", "Support", "Marketing", "Finance", "Operations",
        "Engineering", "HR", "Sales", "Support", "Marketing"
    ],
    "Salary": [
        50000, 75000, 62000, 58000, 80000,
        54000, 52000, 70000, 51000, 64000,
        82000, 53000, 60000, 56000, 68000,
        79000, 49500, 65500, 54500, 61000
    ],
}

df = pd.DataFrame(data)

print(df)

       Name  Age   Department  Salary
0     Alice   25           HR   50000
1       Bob   32  Engineering   75000
2   Charlie   37        Sales   62000
3     David   29    Marketing   58000
4    Evelyn   41  Engineering   80000
5     Frank   28      Finance   54000
6     Grace   34      Support   52000
7     Henry   45   Operations   70000
8      Isla   26           HR   51000
9      Jack   31        Sales   64000
10    Karen   39  Engineering   82000
11      Leo   27      Support   53000
12      Mia   33    Marketing   60000
13     Noah   36      Finance   56000
14   Olivia   30   Operations   68000
15     Paul   42  Engineering   79000
16    Quinn   24           HR   49500
17     Ruby   38        Sales   65500
18      Sam   35      Support   54500
19     Tina   29    Marketing   61000

In [ ]:
#Exercise 1: view the first 5 rows of the DataFrame
df.head()

      Name  Age   Department  Salary
0    Alice   25           HR   50000
1      Bob   32  Engineering   75000
2  Charlie   37        Sales   62000
3    David   29    Marketing   58000
4   Evelyn   41  Engineering   80000

In [ ]:
#Exercise 2: view the last 5 rows of the Dataframe
df.tail()

     Name  Age   Department  Salary
15   Paul   42  Engineering   79000
16  Quinn   24           HR   49500
17   Ruby   38        Sales   65500
18    Sam   35      Support   54500
19   Tina   29    Marketing   61000

In [ ]:
#Exercise 3: Get basic info about the DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        20 non-null     str
 1   Age         20 non-null     int64
 2   Department  20 non-null     str
 3   Salary      20 non-null     int64
dtypes: int64(2), str(2)
memory usage: 772.0 bytes

In [ ]:
#Exercise 4: check the shape of the DataFrame
df.shape

(20, 4)

In [ ]:
#Exercise 1: Use .loc to get the name and age of the passenger with index 12
df.loc[12, ['Name', 'Age']]

Name    Mia
Age      33
Name: 12, dtype: object

In [ ]:
#Exercise 2: Use .iloc to get the first 5 rows and the first 3 columns
df.iloc[0:5, 0:3]

      Name  Age   Department
0    Alice   25           HR
1      Bob   32  Engineering
2  Charlie   37        Sales
3    David   29    Marketing
4   Evelyn   41  Engineering

In [25]:
# Load Titanic dataset directly from GitHub
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

print(df.head())
print(df.columns)

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [21]:
#Exercise 3: Use .loc to get all passengers in 1st class who are female
df.loc[(df['Pclass'] == 1) & (df['Sex'] == 'female')]
#passengers = df[df['Pclass'] == 1]
#df.loc[passengers['female'] 'female']
#df.loc['Pclass', 'Name', 'Sex']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [30]:
#Exercise 4: use .iloc to get the age of the 10th passenger (by position)
df.iloc[9, 5]
print(df.iloc[9, 5])

14.0

In [28]:
print(df.head(11))

    PassengerId  Survived  Pclass  \
0             1         0       3
1             2         1       1
2             3         1       3
3             4         1       1
4             5         0       3
5             6         0       3
6             7         0       1
7             8         0       3
8             9         1       3
9            10         1       2
10           11         1       3

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                              Heikkinen, Miss. Laina  female  26.0      0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                            Allen, Mr. William Henry    male  35.0      0
5                                    Moran, Mr. James    male   NaN      0
6                             McCarthy, Mr. Timothy J    male  54.0      0
7                      Palsson, Master. Gosta Leonard    male   2.0      3
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1

    Parch            Ticket     Fare Cabin Embarked
0       0         A/5 21171   7.2500   NaN        S
1       0          PC 17599  71.2833   C85        C
2       0  STON/O2. 3101282   7.9250   NaN        S
3       0            113803  53.1000  C123        S
4       0            373450   8.0500   NaN        S
5       0            330877   8.4583   NaN        Q
6       0             17463  51.8625   E46        S
7       1            349909  21.0750   NaN        S
8       2            347742  11.1333   NaN        S
9       0            237736  30.0708   NaN        C
10      1           PP 9549  16.7000    G6        S

In [ ]:
#Exercise 5: Use .loc to get the Fare and Survived values for passengers with index 100 to 105
df.loc[df['Fare', 'Survived']]